# CHAPTER03 구형을 위한 도구 (p.89)

In [1]:
import numpy as np
import pandas as pd
import sklearn
import tensorflow
import keras

## 3.1 난수로 이루어진 10,000 x 10,000 형태의 정수 배열을 생성하여라. 이 배열의 요소는 모두 1억 개이며, 원소는 0에서 9사이의 값으로 이루어져 있다.

In [2]:
nparray = np.random.randint(0, 10, size=(10000, 10000))
print(nparray.shape)
nparray

(10000, 10000)


array([[8, 8, 5, ..., 9, 3, 3],
       [9, 1, 1, ..., 3, 6, 4],
       [9, 6, 9, ..., 0, 9, 6],
       ...,
       [9, 9, 5, ..., 6, 7, 5],
       [3, 9, 9, ..., 1, 4, 5],
       [6, 5, 2, ..., 0, 6, 3]])

### 1) 이 배열의 모든 요소를 1 증가시키는 코드를 작성하라.

In [3]:
nparray += 1
nparray

array([[ 9,  9,  6, ..., 10,  4,  4],
       [10,  2,  2, ...,  4,  7,  5],
       [10,  7, 10, ...,  1, 10,  7],
       ...,
       [10, 10,  6, ...,  7,  8,  6],
       [ 4, 10, 10, ...,  2,  5,  6],
       [ 7,  6,  3, ...,  1,  7,  4]])

### 2) 이 배열의 짝수번째 행을 모두 0으로 만들어 행렬을 다음과 같이 만들어 보라.

In [4]:
for i in range(0, nparray.shape[0]):
    if i % 2 == 1:
        nparray[i] = 0
print(nparray.shape)
nparray

(10000, 10000)


array([[ 9,  9,  6, ..., 10,  4,  4],
       [ 0,  0,  0, ...,  0,  0,  0],
       [10,  7, 10, ...,  1, 10,  7],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 4, 10, 10, ...,  2,  5,  6],
       [ 0,  0,  0, ...,  0,  0,  0]])

### 3) 앞 문제의 결과로 얻은 배열에서 홀수번째 열을 모두 0으로 만들어 다음과 같은 행렬을 얻어 보라.

In [5]:
mask = np.array([1] * 10000)
for i in range(0, mask.shape[0]):
    if i % 2 == 0:
        mask[i] = 0
nparray *= mask
print(nparray.shape)
nparray

(10000, 10000)


array([[ 0,  9,  0, ..., 10,  0,  4],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  7,  0, ...,  1,  0,  7],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0, 10,  0, ...,  2,  0,  6],
       [ 0,  0,  0, ...,  0,  0,  0]])

## 3.2 다음은 P 자동차 회사의 차종별(A, B, C,..) 마력, 총중량, 그리고 연비를 나타낸 표이다.
||A|B|C|D|E|F|G|
|:---|---:|---:|---:|---:|---:|---:|---:|
|마력|130|250|190|300|210|220|170|
|총중량|1,900|2,600|2,200|2,900|2,400|2,300|2,200|
|연비|16.3|10.2|11.1|7.1|12.1|13.2|14.2|

### 1) 이 표를 판다스 데이터프레임으로 만들어 다음과 같이 출력해 보라.

In [6]:
name = pd.Series(['A', 'B', 'C', 'D', 'E', 'F', 'G'])
horsepower = pd.Series([130, 250, 190, 300, 210, 220, 170])
weight = pd.Series([1.9, 2.6, 2.2, 2.9, 2.4, 2.3, 2.2])
efficiency = pd.Series([16.3, 10.2, 11.1, 7.1, 12.1, 13.2, 14.2])
df = pd.DataFrame({'name': name, 'horse power': horsepower, 'weight': weight, 'efficiency': efficiency})
print(df)

  name  horse power  weight  efficiency
0    A          130     1.9        16.3
1    B          250     2.6        10.2
2    C          190     2.2        11.1
3    D          300     2.9         7.1
4    E          210     2.4        12.1
5    F          220     2.3        13.2
6    G          170     2.2        14.2


### 2) 이 데이터프레임의 name 열을 인덱스로 지정하여 다음과 같이 고쳐보라.

In [7]:
df2 = df.set_index('name')
print(df2)

      horse power  weight  efficiency
name                                 
A             130     1.9        16.3
B             250     2.6        10.2
C             190     2.2        11.1
D             300     2.9         7.1
E             210     2.4        12.1
F             220     2.3        13.2
G             170     2.2        14.2


### 3) 마력과 연비를 고려하여 차를 선택하려고 한다. 마력과 연비를 곱한 값이 가장 큰 차종을 다음과 같이 찾아 출력하라.
마력과 연비를 곱한 값중 최대값을 가진 차종 : F

In [8]:
df3 = df
df3['h x f'] = df3['horse power'] * df3['efficiency']
print("마력과 연비를 곱한 값중 최대값을 가진 차종 :", df3['name'][df3['h x f'].idxmax()])

마력과 연비를 곱한 값중 최대값을 가진 차종 : F
