### 9주차 인공신경망의 최적화

#### 3.3 활성함수 - 소프트맥스 함수

i = 1, ... , K일 때  $ \sigma (z_i) = {e^{z_i} \over \sum^K_{j=1} e^{z_i}} $

In [1]:
import numpy as np

def softmax(a):
  exp_of_a = np.exp(a)        # 각각의 지수 함수
  sum_exp = np.sum(exp_of_a)  # 지수 함수값의 합
  y = exp_of_a / sum_exp      # 각각의 확률값을 구함
  return y

a = np.array([0.5, 4.1, 2.5, 5.6, 1.2])
print('신경망의 예측값 :', a)
print('소프트맥스 함수의 출력 :', softmax(a))

신경망의 예측값 : [0.5 4.1 2.5 5.6 1.2]
소프트맥스 함수의 출력 : [0.00473882 0.17343248 0.03501541 0.77727047 0.00954281]


소프트맥스 함수는 지수함수이므로 입력값 a가 다음과 같이 두 배로 커질 경우 최대값의 확률값이 크게 증가함

In [2]:
# 소프트맥스 함수의 입력값을 두 배로 증가시켜보자
a = np.array([0.5, 4.1, 2.5, 5.6, 1.2]) * 2
print('신경망의 예측값 :', a)
print('소프트맥스 함수의 출력 :', softmax(a))
print('소프트맥스 함수의 최대값 :', np.max(softmax(a)))
print('소프트맥스 함수의 최대값 idx :', np.argmax(softmax(a)))

신경망의 예측값 : [ 1.   8.2  5.  11.2  2.4]
소프트맥스 함수의 출력 : [3.53328547e-05 4.73259126e-02 1.92910850e-03 9.50566364e-01
 1.43281791e-04]
소프트맥스 함수의 최대값 : 0.9505663642857384
소프트맥스 함수의 최대값 idx : 3


In [3]:
from tensorflow.keras.utils import to_categorical

data = np.array([0, 1, 2, 3, 4])  # 수치 데이터 0에서 4까지의 값
print("인코딩할 원본 데이터", data)
encoded = to_categorical(data)    # 원-핫 인코딩된 범주형 데이터 생성
print("원-핫 인코딩된 데이터 :")
print(encoded)

인코딩할 원본 데이터 [0 1 2 3 4]
원-핫 인코딩된 데이터 :
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
import numpy as np

# 정답 3이 인코딩된 target과 신경망의 예측값 y_hat이 있다고 가정하자
target = np.array([0, 0, 0, 1, 0])
y_hat = np.array([0.005, 0.173, 0.035, 0.777, 0.01])

def mse(y, t):    # 평균제곱오차
  return ((y-t)**2).mean()

print('y_hat과 target과의 오차 :', mse(y_hat, target))

y_hat과 target과의 오차 : 0.016201599999999997


평균 제곱 오차 함수는 범주형 데이터에 대하여, 다음과 같이 정답 레이블과 예측값의 차이의 제곱의 합을 구한 다음 전체 샘플의 개수로 나누어 계산

$ E_{mse} = {1 \over m} {\sum}^m_{i=1} (\hat y_i - y_i)^2 $

In [5]:
# 정답에서 많이 벗어난 other_y_hat 추정치
other_y_hat = np.array([0.2, 0.3, 0.4, 0.01, 0.09])
# other_y_hat 추정치와 정답과의 오차를 알아보자
print('other_y_hat과 target과의 오차 :', mse(other_y_hat, target))

other_y_hat과 target과의 오차 : 0.25564


교차 엔트로피 오차를 구하기 위해서는 다음과 같이 로그의 밑이 e인 자연로그를 예측값 y<sub>k</sub>에 씌워서 목표값 t<sub>k</sub>과 곱한 후 전체 값을 합한 후 음수로 변환

$ E_{cee} = -{\sum}_k {t_k} \log {y_k} $